import { _electron as electron } from '@playwright/test';
import { mkdir, writeFile, mkdtemp } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
const profile = await mkdtemp(path.join(os.tmpdir(), 'cation-smoke-profile-'));
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import electronPath from 'electron';
await mkdir('artifacts', { recursive: true });
const app = await electron.launch({ executablePath: process.env.VIEWER_EXECUTABLE, args: [...(process.env.VIEWER_EXECUTABLE ? [] : ['.']), path.resolve('artifacts/fixtures/sample.glb'), `--user-data-dir=${profile}`], env: { ...process.env, ELECTRON_ENABLE_LOGGING: '1' } });
try {
  const page = await app.firstWindow();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.waitForFunction(() => document.querySelector('#filename')?.textContent === 'sample.glb');
  console.log('Command-line file opening passed.');
  await app.evaluate(({ Menu }) => Menu.getApplicationMenu().items[0].submenu.items.find(item => item.label === 'Load 3D demo').click());
  await page.locator('#stats').filter({ hasText: '3 meshes' }).waitFor();
  await page.screenshot({ path: 'artifacts/electron-demo.png' });
  await page.getByRole('button', { name: 'Wireframe', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Wireframe', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', { name: 'Normals', exact: true }).click();
  await page.screenshot({ path: 'artifacts/electron-normals.png' });
  await page.getByRole('button', { name: 'Materials', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Show Ring', exact: true }).uncheck();
  assert.equal(await page.getByRole('checkbox', { name: 'Show Ring', exact: true }).isChecked(), false);
  await page.getByRole('button', { name: 'Show all', exact: true }).click();
  await page.getByRole('button', { name: 'Play animation', exact: true }).click();
  await page.waitForFunction(() => Number(document.querySelector('#seek').value) > 0.1);
  await page.getByRole('button', { name: 'Pause animation', exact: true }).click();
  await page.locator('#seek').evaluate(input => { input.value = '2.5'; input.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.match(await page.locator('#time').textContent(), /2.50/);
  await page.keyboard.press('7');
  await page.locator('#fit').click();
  await page.locator('#search').fill('Ring');
  assert.equal(await page.locator('.tree-row').count(), 1);
  await page.locator('#search').fill('');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1536, 1024));
  await page.screenshot({ path: 'artifacts/electron-desktop.png' });
  for (const name of ['sample.glb', 'sample.gltf', 'sample.fbx', 'sample.obj', 'sample.stl', 'sample.ply', 'sample.blend', 'compressed.glb']) {
    await page.locator('#file-input').setInputFiles(path.resolve(`artifacts/fixtures/${name}`));
    await page.waitForFunction(name => document.querySelector('#filename').textContent === name, name, { timeout: 130000 });
    assert.equal(await page.locator('#loading').isVisible(), false);
    assert.equal(await page.locator('#message').isVisible(), false, `Unexpected warning for ${name}: ${await page.locator('#message').textContent()}`);
    console.log(`Loaded ${name}: ${await page.locator('#stats').textContent()}`);
  }
  const cdp = await page.context().newCDPSession(page);
  const drag = { items: [], files: [path.resolve('artifacts/fixtures/sample.obj')], dragOperationsMask: 1 };
  for (const type of ['dragEnter', 'dragOver', 'drop']) await cdp.send('Input.dispatchDragEvent', { type, x: 600, y: 400, data: drag });
  await page.waitForFunction(() => document.querySelector('#filename').textContent === 'sample.obj');
  console.log('Native file drag-and-drop passed.');
  await writeFile('artifacts/fixtures/broken.glb', 'invalid');
  await page.locator('#file-input').setInputFiles(path.resolve('artifacts/fixtures/broken.glb'));
  await page.locator('#message').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#filename').textContent(), 'sample.obj');
  await app.evaluate(({ Menu }) => Menu.getApplicationMenu().items[0].submenu.items.find(item => item.label === 'Load 3D demo').click());
  assert.equal(await page.locator('#filename').textContent(), 'Demo scene');
  const childEnv = { ...process.env }; delete childEnv.ELECTRON_RUN_AS_NODE;
  const second = spawn(process.env.VIEWER_EXECUTABLE || electronPath, [...(process.env.VIEWER_EXECUTABLE ? [] : ['.']), path.resolve('artifacts/fixtures/sample.fbx'), `--user-data-dir=${profile}`], { env: childEnv, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  second.stderr.on('data', data => console.log(data.toString()));
  await page.waitForFunction(() => document.querySelector('#filename').textContent === 'sample.fbx');
  assert.equal(app.windows().length, 1);
  console.log('Second-instance file forwarding passed.');
  assert.deepEqual(errors, []);
  console.log('Electron UI smoke passed: modes, visibility, animation, seek, views, search; no renderer errors.');
} finally { await app.close(); }
