const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  open: mediaType => ipcRenderer.invoke('model:dialog', mediaType),
  dropped: file => ipcRenderer.invoke('model:open', webUtils.getPathForFile(file)),
  ready: () => ipcRenderer.invoke('model:ready'),
  acceptTextures: id => ipcRenderer.invoke('textures:accept', id),
  blender: () => ipcRenderer.invoke('blender:select'),
  defaults: () => ipcRenderer.invoke('windows:defaults'),
  state: state => ipcRenderer.invoke('app:state', state),
  contextMenu: state => ipcRenderer.invoke('media:context', state),
  imageContextMenu: state => ipcRenderer.invoke('image:context', state),
  save: payload => ipcRenderer.invoke('export:save', payload),
  saveMeshes: payload => ipcRenderer.invoke('export:meshes', payload),
  saveSourceTextures: payload => ipcRenderer.invoke('export:source-textures', payload),
  processAudio: payload => ipcRenderer.invoke('audio:process', payload),
  importAudio: () => ipcRenderer.invoke('audio:import'),
  importAudioFile: file => ipcRenderer.invoke('audio:import-file', webUtils.getPathForFile(file)),
  videoPreview: id => ipcRenderer.invoke('video:preview', id),
  imageBrowse: (id, relative) => ipcRenderer.invoke('image:browse', id, relative),
  imageLocations: () => ipcRenderer.invoke('image:locations'),
  imageTreeContext: (id, relative) => ipcRenderer.invoke('image:tree-context', id, relative),
  imageTreeLocation: id => ipcRenderer.invoke('image:tree-location', id),
  imageTreeBranch: (id, relative) => ipcRenderer.invoke('image:tree-branch', id, relative),
  imageOpenLocation: id => ipcRenderer.invoke('image:open-location', id),
  imageAncestor: (id, relative, levels) => ipcRenderer.invoke('image:ancestor', id, relative, levels),
  imageChooseFolder: () => ipcRenderer.invoke('image:choose-folder'),
  imageOpenEntry: (id, relative) => ipcRenderer.invoke('image:open-entry', id, relative),
  imageCopyName: (id, relative) => ipcRenderer.invoke('image:copy-name', id, relative),
  imageRename: (id, relative, name, context) => ipcRenderer.invoke('image:rename', id, relative, name, context),
  imageStartDrag: (id, relative, relatives) => ipcRenderer.send('image:start-drag', id, relative, relatives),
  imageRead: (id, relative) => ipcRenderer.invoke('image:read', id, relative),
  imageDecode: (id, relative, thumbnail) => ipcRenderer.invoke('image:decode', id, relative, thumbnail),
  saveImage: (id, payload) => ipcRenderer.invoke('image:save', id, payload),
  imageSaveChanges: (id, payload) => ipcRenderer.invoke('image:save-changes', id, payload),
  saveImageAtlas: (id, payload) => ipcRenderer.invoke('image:save-atlas', id, payload),
  imageFullscreen: fullscreen => ipcRenderer.invoke('image:fullscreen', fullscreen),
  confirmImageDiscard: () => ipcRenderer.invoke('image:discard'),
  closeAfterImageSave: saved => ipcRenderer.invoke('image:close-saved', saved),
  saveVideoFrame: payload => ipcRenderer.invoke('video:frame', payload),
  exportVideo: payload => ipcRenderer.invoke('video:export', payload),
  extractVideoAudio: payload => ipcRenderer.invoke('video:audio', payload),
  exportAudio: payload => ipcRenderer.invoke('audio:export', payload),
  confirmAudioDiscard: () => ipcRenderer.invoke('audio:discard'),
  closeAfterAudioSave: saved => ipcRenderer.invoke('audio:close-saved', saved),
  saveTextures: payload => ipcRenderer.invoke('export:textures', payload),
  texture: () => ipcRenderer.invoke('texture:dialog'),
  onCommand: callback => { const listener = (_, data) => callback(data); ipcRenderer.on('app:command', listener); return () => ipcRenderer.removeListener('app:command', listener); },
  onOpen: callback => { const listener = (_, data) => callback(data); ipcRenderer.on('model:file', listener); return () => ipcRenderer.removeListener('model:file', listener); },
  onImageFullscreen: callback => { const listener = (_, value) => callback(value); ipcRenderer.on('image:fullscreen', listener); return () => ipcRenderer.removeListener('image:fullscreen', listener); },
  onImageDragError: callback => { const listener = (_, value) => callback(value); ipcRenderer.on('image:drag-error', listener); return () => ipcRenderer.removeListener('image:drag-error', listener); }
});
