import metadata from '../../package.json';
import { styleDialog } from './Dialog.mjs';
import { toolButton, toolIcon, panelDivider } from './Controls.mjs';
function modeIcon(mode) {
  return `<span class="view-mode-icon view-mode-${mode}" aria-hidden="true"></span>`;
}
const shadingButtons = [['normals', 'Normals'], ['wire', 'Wireframe'], ['solid', 'Solid'], ['materials', 'Materials'], ['vertex', 'Vertex colors'], ['weights', 'Bone weights']].map(([mode, label]) => `<button data-mode="${mode}" aria-label="${label}" title="${label}" aria-pressed="${mode === 'materials'}">${modeIcon(mode)}</button>`).join('');
const toolIcons = { select: 'pointer', translate: 'arrows-move', rotate: 'rotate-clockwise', scale: 'arrows-diagonal' };
const toolButtons = [['select', 'Select'], ['translate', 'Move'], ['rotate', 'Rotate'], ['scale', 'Scale']].map(([mode, label]) => toolButton({ label, icon: toolIcons[mode], attributes: `data-tool="${mode}" aria-pressed="${mode === 'translate'}"` })).join('');
export function renderLayout(host) {
  host.innerHTML = `
  <header><div class="brand"><img src="./icon.png" alt="" width="30" height="30"><strong>CationMedia</strong><span>Media viewer</span></div><span id="filename">Demo scene</span><button id="open" class="primary">Open file <kbd>Ctrl O</kbd></button></header>
  <main>
    <aside class="scene-panel" data-capability="scene"><div class="panel-heading"><h2>Scene</h2><button id="show-all" class="quiet" title="Show all objects">Show all</button></div><div class="search"><input id="search" type="search" placeholder="Find an object…" aria-label="Find an object"></div><div id="tree" role="group" aria-label="Scene objects"></div><div class="sidebar-note">Select a texture target. Double-click to frame.</div></aside>
    ${panelDivider('left', 'Resize scene panel')}
    <section data-media-view="model3d" class="workspace" aria-label="3D viewport"><div id="viewport"></div><div class="viewport-overlay"><nav class="tools" aria-label="Selection tools" data-capability="transform">${toolButtons}</nav></div><nav data-capability="shading" class="modes" aria-label="Shading mode">${shadingButtons}</nav><button id="fit" class="frame-button" title="Frame model (F)">Frame <kbd>F</kbd></button><div class="navigation-hint">Click to select · Drag to orbit · Scroll to zoom</div><div id="loading" hidden><span class="spinner"></span><span>Opening…</span></div><div id="drop-overlay" hidden><strong>Drop a model or textures</strong><span>3D models · PNG · JPG · WebP · PSD · TIFF</span></div></section>
    ${panelDivider('right', 'Resize display panel')}
    <aside data-media-view="model3d" class="display-panel"><h2>Display</h2><label class="field">Background<input id="background" type="color" value="#18181c" aria-label="Background color"></label><label class="field">Exposure <output id="exposure-value">1.0</output></label><input id="exposure" type="range" min="0.2" max="3" step="0.1" value="1" aria-label="Exposure"><label class="check"><input id="grid" type="checkbox" checked>Floor grid</label><label class="check"><input id="rotate" type="checkbox">Auto rotate</label><hr><div class="viewport-stats"><strong id="stats-title">Model</strong><span id="stats"></span><span id="projection">Perspective</span></div><section data-capability="animation" class="animation-panel" aria-label="Animation controls"><h2>Animation</h2><div class="animation-controls"><select id="clips" aria-label="Animation clip"></select><button id="play" class="primary" aria-label="Play animation">Play</button><span id="time">0.00 / 5.00 s</span><input id="seek" type="range" min="0" max="5" step="0.001" value="0" aria-label="Animation timeline"><label for="speed">Speed</label><select id="speed" aria-label="Playback speed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></div></section><section id="material-panel" class="material-panel" data-capability="materials" hidden></section><div class="spacer"></div><span id="status" role="status" aria-live="polite">Ready</span></aside>
  </main>
  <div id="notifications"><div id="texture-offer" class="texture-offer" role="status" hidden><div><strong>Textures found nearby</strong><span id="texture-offer-description"></span></div><button id="use-found-textures" class="primary">Use textures</button><button id="dismiss-found-textures" aria-label="Dismiss texture suggestion">Dismiss</button></div>
  <div id="message" role="alert" hidden><span></span><button aria-label="Dismiss message">Close</button></div></div><input id="file-input" type="file" accept=".glb,.gltf,.json,.fbx,.obj,.blend,.stl,.ply,.dae,.3ds,.png,.jpg,.jpeg,.webp,.bmp,.gif,.psd,.tif,.tiff" multiple hidden>
  <dialog id="defaults-dialog"><h2>Set as default app</h2><ol><li>Install CationMedia using the Windows installer.</li><li>Open Windows Settings → Apps → Default apps.</li><li>Search for <strong>.jpeg</strong>, <strong>.png</strong>, <strong>.wav</strong> or <strong>.glb</strong> in the file type field at the top.</li><li>Choose CationMedia and confirm. Repeat for other image, audio, video or 3D formats.</li></ol><p>If the app is missing, right-click a media file in Explorer → Open with → Choose another app → Choose an app on your PC, then select <strong>CationMedia.exe</strong> and choose <strong>Always</strong>.</p><p>The updated installer also registers CationMedia in the application list. Reinstall the updated package if an older version is installed.</p><div class="dialog-actions"><button id="open-default-settings" class="primary">Open Windows Settings</button><button id="close-defaults">Close</button></div></dialog>
  <dialog id="about-dialog"><h2>About CationMedia</h2><div class="about-content"><img src="./icon.png" width="72" height="72" alt=""><strong>CationMedia</strong><span class="about-version">Version ${metadata.version}</span></div><div class="dialog-actions"><button id="close-about">Close</button></div></dialog>`;
  host.querySelector('#grid').closest('label').insertAdjacentHTML('afterend', '<label class="check"><input id="show-bones" type="checkbox" disabled>Show bones</label><label id="weight-bone-field" class="field" hidden>Bone <select id="weight-bone" aria-label="Bone for weight colors"></select></label>');
  host.querySelectorAll('dialog').forEach(styleDialog);
}
